# **NUMPY**

# NumPy Array'i Oluşturmak

In [19]:
import numpy as np

In [20]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [21]:
a = np.array([1,2,3,4,5])

In [22]:
type(a)

numpy.ndarray

In [26]:
b = np.array([1.1,2,3,4,5] , dtype = "int")

In [27]:
b

array([1, 2, 3, 4, 5])

## Sıfırdan Array Oluşturma

In [78]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.ones((3,5) , dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.full((3,5) , 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [252]:
np.arange(0, 31, 5)

array([ 0,  5, 10, 15, 20, 25, 30])

In [40]:
np.linspace(0, 100, 5, dtype = "int")

array([  0,  25,  50,  75, 100])

In [76]:
np.random.randint(0, 10000, 3)

array([9076, 2998, 9800])

### özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [79]:
import numpy as np

In [85]:
a = np.random.randint(10, size = 10) # ilk parametreyi boş bırakırsan başlangıcı otomatik olarak sıfır alıyor.

In [86]:
a.ndim

1

In [87]:
a.shape

(10,)

In [88]:
a.size

10

In [89]:
a.dtype

dtype('int32')

In [91]:
b = np.random.randint(10, size = (3, 5))

In [95]:
b

array([[4, 1, 0, 4, 1],
       [6, 6, 4, 3, 0],
       [9, 3, 7, 1, 8]])

In [93]:
b.ndim

2

In [94]:
b.size

15

In [96]:
b.shape

(3, 5)

## Yeniden Şekillendirme (Reshape)

In [97]:
import numpy as np

In [108]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a = np.arange(1, 10)

In [113]:
a.ndim

1

In [117]:
b = a.reshape(1, 9)

In [118]:
b.ndim

2

## Array Birleştirme(Concatenate)

In [184]:
import numpy as np

In [185]:
x = np.arange(1, 4)
y = np.arange(4, 7)

In [186]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [187]:
z = np.arange(7, 10)

In [188]:

np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### iki boyutta reshape

In [189]:
a = np.arange(1, 7).reshape(2, 3)

In [190]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
x = np.concatenate([a, a])
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [194]:
y = np.concatenate([a, a], axis = 1)
y

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma(Split)

In [145]:
import numpy as np

In [146]:
x = np.array([1,2,3,99,99,3,2,1])

In [154]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [155]:
a, b, c = np.split(x, [3, 5])

In [158]:
print("a: ",a)
print("b: ",b)
print("c: ",c)

a:  [1 2 3]
b:  [99 99]
c:  [3 2 1]


### iki boyutlu ayırma

In [161]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [163]:
ust, alt = np.vsplit(m, [2]) 

In [164]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [165]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [166]:
ust, alt = np.hsplit(m, [2]) 

In [167]:
ust

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [168]:
alt

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [171]:
import numpy as np

In [172]:
v = np.array([2,1,4,5,3])
v

array([2, 1, 4, 5, 3])

In [173]:
np.sort(v)

array([1, 2, 3, 4, 5])

### iki boyutlu 

In [221]:
m = np.random.normal(20, 5)

In [177]:
m

array([[16.56811031, 21.52565506, 20.95385373],
       [15.77455459, 29.39262077,  4.75338306],
       [21.41653047, 23.97339663, 18.05289438]])

In [180]:
np.sort(m, axis = 1) ## axis = 0 yaparsan sütuna göre sıralar

array([[16.56811031, 20.95385373, 21.52565506],
       [ 4.75338306, 15.77455459, 29.39262077],
       [18.05289438, 21.41653047, 23.97339663]])

## Index ile Elemanlara Erişmek

In [212]:
import numpy as np
a = np.random.randint(10, size = (10))
a

array([9, 1, 9, 1, 4, 9, 0, 9, 4, 6])

In [213]:
a[0] = 100
a

array([100,   1,   9,   1,   4,   9,   0,   9,   4,   6])

In [214]:
m = np.random.randint(10, size = (3, 5))
m

array([[9, 1, 8, 4, 0],
       [0, 2, 8, 4, 0],
       [0, 1, 4, 0, 6]])

In [216]:
m[0,2]

8

## Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [223]:
import numpy as np
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [224]:
a[0:3] ## veya a[:3]

array([20, 21, 22])

In [239]:
a[3::2]

array([23, 25, 27, 29])

In [238]:
a[::2]

array([20, 22, 24, 26, 28])

### iki boyutlu slice işlemleri

In [250]:
m = np.random.randint(10, size = (5,5))
m

array([[3, 0, 3, 0, 5],
       [4, 5, 2, 4, 7],
       [6, 4, 9, 9, 0],
       [0, 4, 1, 0, 3],
       [1, 8, 3, 8, 9]])

In [270]:
m[0:3, 3]

array([0, 4, 9])

In [269]:
m[0:2, 0:3]

array([[3, 0, 3],
       [4, 5, 2]])

## Alt Küme Üzerinde İşlem Yapmak

In [273]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[9, 3, 1, 7, 8],
       [8, 9, 7, 0, 9],
       [6, 5, 6, 8, 7],
       [9, 0, 9, 0, 4],
       [8, 6, 4, 9, 7]])

In [274]:
alt_a = a[0:3, 0:2]
alt_a

array([[9, 3],
       [8, 9],
       [6, 5]])

In [277]:
alt_a[0,0] = 999
alt_a[1,1] = 888

In [278]:
alt_a

array([[999,   3],
       [  8, 888],
       [  6,   5]])

In [280]:
a # ana array'de değişiyor!!

array([[999,   3,   1,   7,   8],
       [  8, 888,   7,   0,   9],
       [  6,   5,   6,   8,   7],
       [  9,   0,   9,   0,   4],
       [  8,   6,   4,   9,   7]])

In [281]:
m = np.random.randint(10, size = (5,5))
m

array([[7, 8, 7, 5, 3],
       [4, 0, 0, 8, 5],
       [3, 0, 2, 8, 6],
       [3, 2, 4, 5, 0],
       [8, 3, 7, 4, 5]])

In [288]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[7, 8],
       [4, 0],
       [3, 0]])

In [291]:
alt_b[0,0] = 999
alt_b[1,1] = 888
alt_b

array([[999,   8],
       [  4, 888],
       [  3,   0]])

In [292]:
m # copy metodundan dolayı değişmez!!!

array([[7, 8, 7, 5, 3],
       [4, 0, 0, 8, 5],
       [3, 0, 2, 8, 6],
       [3, 2, 4, 5, 0],
       [8, 3, 7, 4, 5]])

## Fancy Index ile Elemanlara Erişmek

In [294]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [295]:
v[1]

3

In [296]:
[v[1],v[3], v[5]]

[3, 9, 15]

In [297]:
al_getir = [1,3,5]

In [298]:
v[al_getir]

array([ 3,  9, 15])

### iki boyutta fancy

In [307]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [308]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [309]:
m[satir, sutun]

array([1, 5])

In [312]:
# basit index ile fancy index

In [310]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [311]:
m[0, [1,2]]

array([1, 2])

In [316]:
# slice ile fancy index

In [314]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri

In [318]:
import numpy as np
v = np.arange(1, 6)
v 

array([1, 2, 3, 4, 5])

In [319]:
v > 5

array([False, False, False, False, False])

In [320]:
v > 3

array([False, False, False,  True,  True])

In [321]:
v[v > 3]

array([4, 5])

In [322]:
v[v != 3]

array([1, 2, 4, 5])

In [323]:
v * 2

array([ 2,  4,  6,  8, 10])

In [324]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [325]:
v**2

array([ 1,  4,  9, 16, 25])

## Matematiksel İşlemler

In [327]:
import numpy as np
v = np.arange(1, 6) ## np.array([1,2,3,4,5]) -> aynı şey
v 

array([1, 2, 3, 4, 5])

In [328]:
v - 1

array([0, 1, 2, 3, 4])

In [329]:
np.subtract(v ,1)

array([0, 1, 2, 3, 4])

In [331]:
v + 1

array([2, 3, 4, 5, 6])

In [332]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [333]:
v * 3

array([ 3,  6,  9, 12, 15])

In [334]:
np.multiply(v, 3)

array([ 3,  6,  9, 12, 15])

In [335]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [336]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [337]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [343]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [346]:
np.absolute([-1, -1221 , -22, 123 , 0, 12121]) ## mutlak değer -> veya np.absolute(np.array([-3]))

array([    1,  1221,    22,   123,     0, 12121])

In [355]:
np.sin(360)

0.9589157234143065

In [356]:
np.cos(180)

-0.5984600690578581

In [357]:
v = np.array([1,2,3,4,5])

In [358]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [360]:
#cheatsheet !!!

## NumPy ile İki Bilinmeyenli Denklem Çözümü

In [361]:
import numpy as np

**5 * x0 + x1 = 12**

**x0 + 3 * x1 = 10**

In [364]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [365]:
a

array([[5, 1],
       [1, 3]])

In [366]:
b

array([12, 10])

In [367]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

x0 = 1.85714286

x1 = 2.71428571

# **PANDAS**

# Pandas Serisi Oluşturmak

In [368]:
import pandas as pd

In [373]:
seri = pd.Series([10,2,31,4,5])
seri

0    10
1     2
2    31
3     4
4     5
dtype: int64

In [375]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [376]:
seri.dtype

dtype('int64')

In [377]:
seri.size

5

In [378]:
seri.ndim

1

In [380]:
seri.values

array([10,  2, 31,  4,  5], dtype=int64)

In [382]:
seri.head(3)

0    10
1     2
2    31
dtype: int64

In [384]:
seri.tail(2) #sondan bakar

3    4
4    5
dtype: int64

### index isimlendirmesi

In [385]:
pd.Series([99,22,33,123,83])

0     99
1     22
2     33
3    123
4     83
dtype: int64

In [388]:
pd.Series([99,22,33,123,83], index = [1,2,3,"d","e"])

1     99
2     22
3     33
d    123
e     83
dtype: int64

In [389]:
seri = pd.Series([99,22,33,123,83], index = [1,2,3,"d","e"])

In [391]:
seri["d"]

123

In [393]:
seri[1:"d"]

1     99
2     22
3     33
d    123
dtype: int64

### sözlük üzerinden liste oluşturmak

In [398]:
sozluk = pd.Series({"furkan": 1, "memet": 2, 31 : "3131"}) # veya önce sözlük tanımlayıp sonra pd.Series(sözlük) yazarak oluşturulabilir.
sozluk

furkan       1
memet        2
31        3131
dtype: object

### iki seri birleştirerek seri oluşturmak

In [399]:
pd.concat([seri,seri])

1     99
2     22
3     33
d    123
e     83
1     99
2     22
3     33
d    123
e     83
dtype: int64

## Eleman Oluşturma

In [401]:
import numpy as np
a = np.array([11,20,23,41,56])
seri = pd.Series(a)
seri

0    11
1    20
2    23
3    41
4    56
dtype: int32

In [402]:
seri[0]

11

In [403]:
seri[1:3]

1    20
2    23
dtype: int32

In [409]:
seri = pd.Series([121, 99, 1012, 1244], 
                 index = ["reg", "loj", "rfg", "abc"])
seri

reg     121
loj      99
rfg    1012
abc    1244
dtype: int64

In [410]:
seri.index

Index(['reg', 'loj', 'rfg', 'abc'], dtype='object')

In [411]:
seri.keys

<bound method Series.keys of reg     121
loj      99
rfg    1012
abc    1244
dtype: int64>

In [413]:
list(seri.items())

[('reg', 121), ('loj', 99), ('rfg', 1012), ('abc', 1244)]

In [415]:
seri.values

array([ 121,   99, 1012, 1244], dtype=int64)

### eleman sorgulama

In [416]:
"reg" in seri

True

In [417]:
"a" in seri

False

### fancy eleman

In [419]:
seri[["reg", "abc"]]

reg     121
abc    1244
dtype: int64

## Pandas DataFrame Oluşturma

In [429]:
import pandas as pd
import numpy as np

In [426]:
l = [12,21,33,44,5123]

In [428]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0             12
1             21
2             33
3             44
4           5123

In [445]:
m = np.arange(10, 20).reshape((5,2))
m

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [446]:
pd.DataFrame(m, columns = ["var1", "var2"])

var1  var2
0    10    11
1    12    13
2    14    15
3    16    17
4    18    19

### df isimlendirme

In [459]:
df = pd.DataFrame(m, columns = ["var1", "var2"])
df.head(3)

var1  var2
0    10    11
1    12    13
2    14    15

In [451]:
df.columns = ("deg1", "deg2")

In [452]:
df

deg1  deg2
0    10    11
1    12    13
2    14    15
3    16    17
4    18    19

In [453]:
df.shape

(5, 2)

In [454]:
df.ndim

2

In [455]:
df.size

10

In [456]:
df.values

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [458]:
type(df.values) ## dikkat edin type array'e döünüştü yukarıdaki işlem ile 

numpy.ndarray

## Eleman İşlemleri

In [500]:
import numpy as np
s1 = np.random.randint(1,100, size  = 10)
s2 = np.random.randint(100,200, size  = 10)
s3 = np.random.randint(1,100, size  = 10)

In [501]:
sozluk = {"var1" : s1, "var2" : s2, "var3" : s3}
sozluk

{'var1': array([37, 88, 38, 77, 30, 71, 43, 45, 24,  9]),
 'var2': array([171, 163, 108, 185, 113, 126, 198, 187, 111, 179]),
 'var3': array([65, 66, 21, 28, 47, 79, 75, 63, 33, 65])}

In [502]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0    37   171    65
1    88   163    66
2    38   108    21
3    77   185    28
4    30   113    47
5    71   126    79
6    43   198    75
7    45   187    63
8    24   111    33
9     9   179    65

In [503]:
df[0:4]

var1  var2  var3
0    37   171    65
1    88   163    66
2    38   108    21
3    77   185    28

In [504]:
df[0::2]

var1  var2  var3
0    37   171    65
2    38   108    21
4    30   113    47
6    43   198    75
8    24   111    33

### silme

In [505]:
df = df.drop(6, axis = 0) # veya df.drop(6, axis = 0, inplace = True) yaparak değişikliği df üzerinde kalıcı hale getirirsin, Literatürde inplace argümanı daha yaygındır.

In [506]:
df[0:10]

var1  var2  var3
0    37   171    65
1    88   163    66
2    38   108    21
3    77   185    28
4    30   113    47
5    71   126    79
7    45   187    63
8    24   111    33
9     9   179    65

In [507]:
df["var4"] = df["var1"] / 2

In [508]:
df

var1  var2  var3  var4
0    37   171    65  18.5
1    88   163    66  44.0
2    38   108    21  19.0
3    77   185    28  38.5
4    30   113    47  15.0
5    71   126    79  35.5
7    45   187    63  22.5
8    24   111    33  12.0
9     9   179    65   4.5

In [509]:
df.drop("var4", axis = 1, inplace = True)

In [510]:
df

var1  var2  var3
0    37   171    65
1    88   163    66
2    38   108    21
3    77   185    28
4    30   113    47
5    71   126    79
7    45   187    63
8    24   111    33
9     9   179    65

## Gözlem ve Değişken Seçimi : loc & iloc

In [520]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df

var1  var2  var3
0    14     3    25
1    17    10    15
2    28    24    24
3    21    24     5
4    12    10     7
5    10    25     2
6     8    17     9
7    24    19     5
8    10    22     7
9    17    17    12

### loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [521]:
df.loc[0:3]

var1  var2  var3
0    14     3    25
1    17    10    15
2    28    24    24
3    21    24     5

### iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [522]:
df.iloc[0:3]

var1  var2  var3
0    14     3    25
1    17    10    15
2    28    24    24

In [523]:
df.iloc[:3, :2]

var1  var2
0    14     3
1    17    10
2    28    24

In [524]:
df.loc[0:3, "var2"]

0     3
1    10
2    24
3    24
Name: var2, dtype: int32

In [530]:
df.iloc[0:4, "var2"] # hata verir "var2" kullanılamaz df.iloc[0:3, 1] şeklinde yazmak lazım

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

## Koşullu eleman işlemleri

In [532]:
df.var1

0    14
1    17
2    28
3    21
4    12
5    10
6     8
7    24
8    10
9    17
Name: var1, dtype: int32

In [537]:
df[df.var1 > 15]["var1"]

1    17
2    28
3    21
7    24
9    17
Name: var1, dtype: int32

In [538]:
df[(df.var1 > 15) & (df.var3 < 15)] 

var1  var2  var3
3    21    24     5
7    24    19     5
9    17    17    12

## Birleştirme (Join) İşlemleri

In [541]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df1

var1  var2  var3
0    11    28    28
1     2    16    13
2    16    15    10
3     4    13    18
4    17    19     5

In [543]:
df2 = df1 + 99
df2

var1  var2  var3
0   110   127   127
1   101   115   112
2   115   114   109
3   103   112   117
4   116   118   104

In [544]:
pd.concat([df1, df2])

var1  var2  var3
0    11    28    28
1     2    16    13
2    16    15    10
3     4    13    18
4    17    19     5
0   110   127   127
1   101   115   112
2   115   114   109
3   103   112   117
4   116   118   104

In [546]:
pd.concat([df1, df2], ignore_index = True)

var1  var2  var3
0    11    28    28
1     2    16    13
2    16    15    10
3     4    13    18
4    17    19     5
5   110   127   127
6   101   115   112
7   115   114   109
8   103   112   117
9   116   118   104

In [547]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [549]:
df2.columns = ["var1", "var2", "deg3"]
df2

var1  var2  deg3
0   110   127   127
1   101   115   112
2   115   114   109
3   103   112   117
4   116   118   104

In [550]:
pd.concat([df1, df2])

var1  var2  var3   deg3
0    11    28  28.0    NaN
1     2    16  13.0    NaN
2    16    15  10.0    NaN
3     4    13  18.0    NaN
4    17    19   5.0    NaN
0   110   127   NaN  127.0
1   101   115   NaN  112.0
2   115   114   NaN  109.0
3   103   112   NaN  117.0
4   116   118   NaN  104.0

In [558]:
pd.concat([df1,df2], join = "inner")

var1  var2
0    11    28
1     2    16
2    16    15
3     4    13
4    17    19
0   110   127
1   101   115
2   115   114
3   103   112
4   116   118

## İleri Birleştirme İşlemleri 

In [559]:
import pandas as pd

### birebir birleştirme

In [592]:
df1 = pd.DataFrame({'calisanlar': ['furkan', 'nida', 'isa', 'dilsad'],
                   'grup': ['muhendis', 'ogretmen', 'soytari', 'soytari']})
df1

calisanlar      grup
0     furkan  muhendis
1       nida  ogretmen
2        isa   soytari
3     dilsad   soytari

In [593]:
df2 = pd.DataFrame({'calisanlar': ['furkan', 'nida', 'isa', 'dilsad'],
                    'ilk_giris': [2025, 2019, 2023, 2024]})
df2

calisanlar  ilk_giris
0     furkan       2025
1       nida       2019
2        isa       2023
3     dilsad       2024

In [594]:
pd.concat([df1, df2])

calisanlar      grup  ilk_giris
0     furkan  muhendis        NaN
1       nida  ogretmen        NaN
2        isa   soytari        NaN
3     dilsad   soytari        NaN
0     furkan       NaN     2025.0
1       nida       NaN     2019.0
2        isa       NaN     2023.0
3     dilsad       NaN     2024.0

In [595]:
pd.merge(df1, df2)

calisanlar      grup  ilk_giris
0     furkan  muhendis       2025
1       nida  ogretmen       2019
2        isa   soytari       2023
3     dilsad   soytari       2024

### çoktan teke

In [596]:
df3 = pd.merge(df1, df2)
df3

calisanlar      grup  ilk_giris
0     furkan  muhendis       2025
1       nida  ogretmen       2019
2        isa   soytari       2023
3     dilsad   soytari       2024

In [602]:
df4 = pd.DataFrame({'grup': ['muhendis', 'ogretmen', 'soytari'],
                   'mudur': ['mudur1', 'mudur2', 'mudur3']})
df4

grup   mudur
0  muhendis  mudur1
1  ogretmen  mudur2
2   soytari  mudur3

In [603]:
pd.merge(df3, df4)

calisanlar      grup  ilk_giris   mudur
0     furkan  muhendis       2025  mudur1
1       nida  ogretmen       2019  mudur2
2        isa   soytari       2023  mudur3
3     dilsad   soytari       2024  mudur3

## Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:
* count
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [604]:
import seaborn as sns

In [607]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [618]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [619]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [620]:
df.shape

(1035, 6)

In [622]:
df["mass"].mean()

2.6381605847953216

In [623]:
df["mass"].count()

513

In [624]:
df["mass"].max()

25.0

In [625]:
df["mass"].sum()

1353.37638

In [626]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [627]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [631]:
df.dropna().describe().T #veri içindeki eksik değerleri görmezden gelir

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

## Gruplama İşlemleri

In [632]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [633]:
df.groupby("gruplar")

In [634]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [635]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [637]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [638]:
df.groupby("method")

In [639]:
df.groupby("method")["orbital_period"]

In [640]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [641]:
df.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [642]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [643]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

### Aggregate

In [645]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [651]:
df.groupby("gruplar").aggregate(["min", np.median, max]) # aggregate ile istediğimiz özelliği seçebiliriz

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [652]:
df.groupby("gruplar").aggregate({"degisken1": min, "degisken2" : max}) 

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

### Filter

In [653]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [664]:
def filter_func(x):
    return x["degisken1"].mean() > 50

In [665]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [666]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

### Transform

In [667]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [676]:
df_a = df.iloc[:,1:3]

In [677]:
df["degisken1"] * 9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [678]:
df_a.transform(lambda x: x-x.mean())

degisken1  degisken2
0      -23.0     -238.0
1      -10.0      -85.0
2        0.0       -5.0
3      -11.0      -76.0
4      -22.0     -227.0
5       66.0      631.0

### Apply

In [691]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [688]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [689]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [692]:
df.groupby("gruplar").apply(np.mean)

gruplar
A     98.5
B     99.5
C    358.5
dtype: float64

# Pivot Tablolar

In [694]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [695]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [696]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

### pivot ile table

In [697]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [698]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [699]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [700]:
titanic.pivot_table("survived", ["sex", age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okumak

In [701]:
import pandas as pd

In [705]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [707]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [709]:
#xlsx okuma
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [710]:
df = pd.read_excel("reading_data/ornekx.xlsx")
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [712]:
df.columns = ("A", "B", "C")
df.head()

A    B    C
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [713]:
tips = pd.read_csv("reading_data/data.txt")

In [714]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# GOOD JOB :)